blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('blog_detail/<int:pk>', BlogDetailView.as_view(), name='blog_detail'),
]

clients/urls.py
from django.urls import path

from clients.apps import ClientsConfig
from clients.views import ClientsListView, ClientsCreateView, ClientsUpdateView, ClientsDetailView, ClientsDeleteView

app_name = ClientsConfig.name

urlpatterns = [
    path('clients_list/', ClientsListView.as_view(), name='clients_list'),
    path('clients_create/', ClientsCreateView.as_view(), name='clients_create'),
    path('clients_update/<int:pk>', ClientsUpdateView.as_view(), name='clients_update'),
    path('clients_detail/<int:pk>', ClientsDetailView.as_view(), name='clients_detail'),
    path('clients_delete/<int:pk>', ClientsDeleteView.as_view(), name='clients_delete'),

]

djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailings.urls', namespace='mailings')),
                  path('users/', include('users.urls', namespace='users')),
                  path('clients/', include('clients.urls', namespace='clients')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from clients.views import LogMailingsView
from mailings.apps import MainConfig
from mailings.views import index, MailingsListView, MailingsCreateView, MailingsUpdateView, MailingsDetailView, \
    MailingsDeleteView

app_name = MainConfig.name

urlpatterns = [
    path('', cache_page(60)(index), name='index'),
    path('mailings_list/', cache_page(60)(MailingsListView.as_view()), name='mailings_list'),
    path('mailings_create/', MailingsCreateView.as_view(), name='mailings_create'),
    path('mailings_update/<int:pk>', MailingsUpdateView.as_view(), name='mailings_update'),
    path('mailings_detail/<int:pk>', MailingsDetailView.as_view(), name='mailings_detail'),
    path('mailings_delete/<int:pk>', MailingsDeleteView.as_view(), name='mailings_delete'),
    path('log_mailings/', cache_page(60)(LogMailingsView.as_view()), name='log_mailings'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, verification_view, recovery_view

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('verification/', verification_view, name='verification'),
    path('recovery/', recovery_view, name='recovery')

]

mailings/models.py
from django.contrib.postgres.fields import JSONField
from django.db import models

from clients.models import Client
from default import NULLABLE
from users.models import User


class Message(models.Model):
    name = models.CharField(max_length=50, verbose_name='заголовок')
    text = models.TextField(verbose_name='тескт сообщения')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Mailings(models.Model):
    day = 'Раз в день'
    week = 'Раз в неделю'
    month = 'Раз в месяц'
    periodicity_choises = [
        (day, 'day'),
        (week, 'week'),
        (month, 'month'),
    ]
    name = models.CharField(default='Рассылка', max_length=150, verbose_name='название рассылки')
    user_creator = models.EmailField(verbose_name='создатель', **NULLABLE)
    message = models.ForeignKey(Message, on_delete=models.CASCADE, default='2')
    clients = models.ManyToManyField(Client, verbose_name='клиенты')
    day_start = models.DateField(verbose_name='дата начала рассылки', **NULLABLE)
    time_to_send = models.TimeField(verbose_name='время рассылки', **NULLABLE)
    periodicity = models.CharField(
        max_length=15,
        choices=periodicity_choises,
        default=day,
    )
    completed = 'Запущена'
    created = 'Создана'
    launched = 'Законченна'

    status_choises = [
        (completed, 'completed'),
        (created, 'created'),
        (launched, 'launched'),
    ]
    status = models.CharField(verbose_name='статус рассылки',
                              max_length=15,
                              choices=status_choises,
                              default=created,
                              )

    def __str__(self):
        return f'{self.name} {self.user_creator}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions = [
            ('set_status', 'может менять статус'),
        ]


class IntersectionMailingsClients(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    mailings = models.ForeignKey(Mailings, on_delete=models.CASCADE)


class LogMailings(models.Model):
    time = models.CharField(verbose_name='время рассылки', **NULLABLE)
    mailings_name = models.CharField(verbose_name='имя рассылки', **NULLABLE)
    message_title = models.CharField(verbose_name='заголовок сообщения', **NULLABLE)
    message_text = models.TextField(verbose_name='текст рассылки', **NULLABLE)
    success = models.BooleanField(verbose_name='успешность отправки', default=False)
    user_created = models.CharField(verbose_name='создатель рассылки', **NULLABLE)

    def __str__(self):
        return f'{self.time} {self.success} , {self.mailings_name}'

    class Meta:
        verbose_name = "лог"
        verbose_name_plural = "логи"

mailings/forms.py
from django import forms

from mailings.models import Mailings, Message


class MailingsForm(forms.ModelForm):
    class Meta:
        model = Mailings
        exclude = ('user_creator',)
        widgets = {
            'time_to_send': forms.TimeInput(attrs={'type': 'time'}),
            'day_start': forms.DateInput(attrs={'type': 'date'}),
        }

    def clean_name(self):
        cleaned_data = self.cleaned_data.get('name')
        if cleaned_data in ['хуй', 'пизда',
                            'хуевый', 'пидар', 'пидарас',
                            'охуели', 'сука', 'суки', 'пидарасы', 'пидары']:
            raise forms.ValidationError("Недопустимое название продукта")
        return cleaned_data

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

mailings/views.py
import random

from django.shortcuts import render
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from blog.models import Blog
from clients.models import Client
from mailings.forms import MailingsForm
from mailings.models import Mailings


def index(request):
    is_active = 0
    for el in Mailings.objects.all():
        if el.status == 'Запущена':
            is_active += 1
    blog_object = Blog.objects.all().order_by('?')[:3]

    context = {
        'context_list': [
            Mailings.objects.all().count(),
            is_active,
            Client.objects.all().count(),
            blog_object,
        ]
    }
    return render(request, 'mailings/index.html', context)


class MailingsListView(ListView):
    model = Mailings
    template_name = 'mailings/mailings_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        if not self.request.user.groups.filter(name='Manager').first():
            queryset = queryset.filter(user_creator=self.request.user)

        return queryset


class MailingsCreateView(CreateView):
    model = Mailings
    form_class = MailingsForm

    def form_valid(self, form):
        self.object = form.save()
        self.object.user_creator = self.request.user.email
        self.object.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('mailings:mailings_list')


class MailingsUpdateView(UpdateView):
    model = Mailings
    form_class = MailingsForm

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        if self.request.user.email != self.object.user_creator:
            mailing_fields = [field for field in form.fields.keys()]
            for field in mailing_fields:
                if not self.request.user.has_perm(f'mailings.set_{field}'):
                    del form.fields[field]
        return form

    def get_success_url(self):
        return reverse('mailings:mailings_list')


class MailingsDetailView(DetailView):
    model = Mailings
    template_name = 'mailings/mailings_detail.html'


class MailingsDeleteView(DeleteView):
    model = Mailings

    def get_success_url(self):
        return reverse('mailings:mailings_list')

mailings/templates/mailings/base.html
<!doctype html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>
        Сайт Рассылок
    </title>


</head>
<body>
<br>
<div class="d-print-table-row">
    <a class="btn btn-primary" href="{% url 'mailings:index' %}" role="button">Главная</a>
    <a class="btn btn-primary" href="{% url 'mailings:index' %}" role="button">Контакты</a>
    {% if user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'users:profile' %}" role="button">Профиль</a>
        <a class="btn btn-primary" href="{% url 'users:logout' %}" role="button">Выйти</a>
        <a class="btn btn-primary" href="{% url 'mailings:mailings_list' %}" role="button">Рассылки</a>
        <a class="btn btn-primary" href="{% url 'clients:clients_list' %}" role="button">Клиенты</a>
    {% else %}
        <a class="btn btn-primary" href="{% url 'users:login' %}" role="button">Войти</a>
        <a class="btn btn-primary" href="{% url 'users:register' %}" role="button">Регистрация</a>
    {% endif %}
    <br>
    <br>
</div>
<h1 class="text-lg-center">Добро пожаловать на сайт рассылок</h1>


{% block content %}
{% endblock %}


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

mailings/templates/mailings/index.html
{% extends 'mailings/base.html' %}

{% block content %}

    <div class="row text-lg-center">
        <div class="col-4">
            <p> Количество рассылок всего: {{ context_list.0 }} </p>
        </div>
        <div class="col-4">

            <p> Количество рассылок активных: {{ context_list.1 }} </p>
        </div>
        <div class="col-4">

            <p> Количество клиентов: {{ context_list.2 }} </p>
        </div>


    </div>
    <div class="conteiner">
        <div class="row">
            <div class="col-12">
                <div class="row">
                    <div class="col-6">
                        {% for object in context_list.3 %}
                            <div class="card">
                                <div class="card-title">
                                    <p>{{ object.title }}</p>
                                </div>
                                <div class="card-body">
                                    <p>Просмотров: {{ object.number_of_views }}</p>
                                    <p>{{ object.date_of_published }}</p>
                                    <p>{{ object.user_creator }}</p>
                                    <p>{{ object.content }}</p>
                                    <p>{{ object.pk }}</p>
                                    <a class="btn btn-lg btn-block btn-outline-primary"
                                       href="{% url 'blog:blog_detail' object.pk %}">
                                        Посмотреть
                                    </a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

mailings/templates/mailings/log_mailings_list.html
{% extends 'mailings/base.html' %}

{% block content %}

    {% if user.is_active %}

        <table class="table">
            <thead>
            <tr>
                <th scope="col">ID рассылки</th>
                <th scope="col">Успешность рассылки</th>
                <th scope="col">Имя рассылки</th>
                <th scope="col">Имя сообщения</th>
                <th scope="col">Время рассылки</th>
                <th scope="col">Создатель рассылки</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                {% if user.email == object.user_created %}
                    <tr>
                        <th scope="row">{{ object.pk }}</th>
                        {% if object.success == True %}
                            <td>Успешно</td>
                        {% else %}
                            <td>Провалено</td>
                            {% endif %}
                        <td>{{ object.mailings_name }}</td>
                        <td>{{ object.message_title }}</td>
                        <td>{{ object.time }}</td>
                        <td>{{ object.user_created }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>

    {% else %}
        <p align="center">Вы не авторизовались. Доступа к продуктам нет.</p>
    {% endif %}

{% endblock %}

mailings/templates/mailings/mailings_confirm_delete.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-3">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить продукт "{{object.title}} ?"</p>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-danger">
                            Подтвердить
                        </button>
                        <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'mailings:mailings_list' %}">
                            ОТМЕНА
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailings/templates/mailings/mailings_detail.html
{% extends 'mailings/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title text-lg-center">{{ object.name }}</h5>
                    <p class="card-text text-sm-center">Периодичность: {{ object.periodicity }}</p>
                    <p class="card-text text-sm-center">Статус: {{ object.created }}</p>
                    <p class="card-text text-sm-center">Автор: {{ object.user_creator }}</p>
                    <p class="card-text text-sm-center">Название рассылки: {{ object.message.name }}</p>
                    <p class="card-text text-sm-center">Текст рассылки: {{ object.message.text }}</p>
                    {% for client in object.clients.all %}
                        <p class="card-text text-sm-center">Данные клиента: {{ client.email }}</p>
                    {% endfor %}
                    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'mailings:mailings_list' %}">
                        Назад
                    </a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

mailings/templates/mailings/mailings_form.html
{% extends 'mailings/base.html' %}

{% block content %}
    <div class="col-12">
        <form method="post">
            <div class="row">
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                Создать
                            </button>
                            <a class="btn btn-outline-primary" href="{% url 'mailings:mailings_list' %}">
                                Назад
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

mailings/templates/mailings/mailings_list.html
{% extends 'mailings/base.html' %}

{% block content %}

    {% if user.is_active %}

        <div class="col-12">
            <div class="row">
                <div class="col-6">
                    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'mailings:mailings_create' %}">
                        Создать рассылку
                    </a>
                </div>
                <div class="col-6">
                    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'mailings:log_mailings' %}">
                        Логи Рассылок
                    </a>
                </div>
            </div>
        </div>
        <br>

        <div class="row">
            {% for object in object_list %}

                    <div class="col-sm-3">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title text-lg-center">{{ object.name }}</h5>
                                <p class="card-text text-sm-center">{{ object.status }}</p>
                                <p class="card-text">{{ object.user_creator.fio }}</p>
                                <a class="btn btn-lg btn-block btn-outline-primary"
                                   href="{% url 'mailings:mailings_detail' object.pk %}">Просмотреть</a>
                                <a class="btn btn-lg btn-block btn-outline-primary"
                                   href="{% url 'mailings:mailings_update' object.pk %}">Редактировать</a>
                                <a class="btn btn-lg btn-block btn-outline-primary"
                                   href="{% url 'mailings:mailings_delete' object.pk %}">Удалить</a>
                            </div>
                        </div>
                    </div>

            {% endfor %}
        </div>

    {% else %}
        <p align="center">Вы не авторизовались. Доступа к продуктам нет.</p>
    {% endif %}

{% endblock %}