blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('blog_detail/<int:pk>', BlogDetailView.as_view(), name='blog_detail'),
]

djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailings.urls', namespace='mailings')),
                  path('users/', include('users.urls', namespace='users')),
                  path('clients/', include('clients.urls', namespace='clients')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from clients.views import LogMailingsView
from mailings.apps import MainConfig
from mailings.views import index, MailingsListView, MailingsCreateView, MailingsUpdateView, MailingsDetailView, \
    MailingsDeleteView

app_name = MainConfig.name

urlpatterns = [
    path('', cache_page(60)(index), name='index'),
    path('mailings_list/', cache_page(60)(MailingsListView.as_view()), name='mailings_list'),
    path('mailings_create/', MailingsCreateView.as_view(), name='mailings_create'),
    path('mailings_update/<int:pk>', MailingsUpdateView.as_view(), name='mailings_update'),
    path('mailings_detail/<int:pk>', MailingsDetailView.as_view(), name='mailings_detail'),
    path('mailings_delete/<int:pk>', MailingsDeleteView.as_view(), name='mailings_delete'),
    path('log_mailings/', cache_page(60)(LogMailingsView.as_view()), name='log_mailings'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, verification_view, recovery_view

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('verification/', verification_view, name='verification'),
    path('recovery/', recovery_view, name='recovery')

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from default import NULLABLE


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    fio = models.CharField(max_length=150, verbose_name='ФИО', **NULLABLE)
    about = models.TextField(verbose_name='коментарии', **NULLABLE)
    token = models.CharField(max_length=22, verbose_name='Token для верификации почты', **NULLABLE)

    is_active = models.BooleanField(default=False, verbose_name='верифицированна')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'email',
            'password1',
            'password2'
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'email',
            'fio',
            'about',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

users/views.py
import secrets

from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from djangoProject import settings
from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:verification')

    def form_valid(self, form):
        token = secrets.token_hex(11)
        user = form.save(commit=False)
        user.token = token
        user.is_active = False
        user.save()

        send_mail(
            subject='Регистрация',
            message=f'Авторизация удалась.  {token}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


def verification_view(request):
    if request.method == 'POST':
        input_key = request.POST.get('token')
        try:
            user = User.objects.get(token=input_key)
            user.is_active = True
            user.save()
        except User.DoesNotExist:
            return render(request, 'users/fail_verif.html')
        return render(request, 'users/success_valid.html')
    return render(request, 'users/verification.html')


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('mailings:index')

    def get_object(self, queryset=None):
        return self.request.user


def recovery_view(request):
    if request.method == 'POST':
        try:
            input_email = request.POST.get('email')

            user = User.objects.get(email=input_email)
            user_password = secrets.token_hex(11)

            user.set_password(user_password)
            user.save()

            send_mail(subject='Восстановление пароля', message=f'Ваш новый пароль  {user_password}',
                      from_email=settings.EMAIL_HOST_USER, recipient_list=[user.email], )
            return redirect('users:login')
        except:
            return render(request, 'users/unsuccess_valid.html')

    return render(request, 'users/recovery.html')

users/templates/users/fail_verif.html
{% extends 'mailings/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-lg-3">
            <h4>
                Что то пошло не так!
            </h4>
        </div>

    </div>

{% endblock %}

users/templates/users/login.html
{% extends 'mailings/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="flex-xl-row" method="post", enctype="multipart/form-data">
            <div class="row">
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                Вход
                            </h3>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                Войти
                            </button>
                            <a class="btn btn-outline-primary" href="{% url 'mailings:index' %}">Назад</a>
                            <a class="btn btn-outline-primary" href="{% url 'users:recovery' %}">Восстановить пароль</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

users/templates/users/recovery.html
{% extends 'mailings/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3>
                        Введите электронную почту
                    </h3>
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <input type="text" name="email" class="form-control" id="email"
                                   placeholder="Введите ваш email"
                                   required>
                        </div>

                        <button type="submit" class="btn btn-primary">
                            Подтвердить
                        </button>

                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/register.html
{% extends 'mailings/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="flex-xl-row" method="post", enctype="multipart/form-data">
            <div class="row">
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                Регистрация
                            </h3>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                Регистрация
                            </button>
                            <a class="btn btn-outline-primary" href="{% url 'mailings:index' %}">Назад</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

users/templates/users/success_valid.html
{% extends 'mailings/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-lg-3">
            <h4>
                Спасибо что воспользовались нашим сервисом авторизация прошла успешно!
            </h4>
            <a href="{% url 'mailings:index' %}">Перейти к продукту</a>
        </div>

    </div>

{% endblock %}

users/templates/users/unsuccess_valid.html
{% extends 'mailings/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="flex-xl-row" method="post" , enctype="multipart/form-data">
            <div class="row">
                <div class="col-6">
                    <div class="card">
                        <div class="title">Введен неверный Email.</div>
                        <div class="body">
                            <a class="btn btn-outline-primary" href="{% url 'users:recovery' %}">Восстановить пароль</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'mailings/base.html' %}
{% block content %}

    <div class="col-12">
        <form class="flex-xl-row" method="post", enctype="multipart/form-data">
            <div class="row">
                <div class="col-6">
                    <div class="card">

                        <div class="card-header">
                            <h3 class="card-title">
                                Профиль
                            </h3>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                Сохранить
                            </button>
                            <a class="btn btn-outline-primary" href="{% url 'mailings:index' %}">Назад</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

users/templates/users/verification.html
{% extends 'mailings/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3>
                        Подтверждение электронной почты
                    </h3>
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <input type="text" name="token" class="form-control" id="token"
                                   placeholder="Введите код из письма"
                                   required>
                        </div>
                        <button type="submit" class="btn btn-primary">Подтвердить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}