blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('blog_detail/<int:pk>', BlogDetailView.as_view(), name='blog_detail'),
]

clients/urls.py
from django.urls import path

from clients.apps import ClientsConfig
from clients.views import ClientsListView, ClientsCreateView, ClientsUpdateView, ClientsDetailView, ClientsDeleteView

app_name = ClientsConfig.name

urlpatterns = [
    path('clients_list/', ClientsListView.as_view(), name='clients_list'),
    path('clients_create/', ClientsCreateView.as_view(), name='clients_create'),
    path('clients_update/<int:pk>', ClientsUpdateView.as_view(), name='clients_update'),
    path('clients_detail/<int:pk>', ClientsDetailView.as_view(), name='clients_detail'),
    path('clients_delete/<int:pk>', ClientsDeleteView.as_view(), name='clients_delete'),

]

djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailings.urls', namespace='mailings')),
                  path('users/', include('users.urls', namespace='users')),
                  path('clients/', include('clients.urls', namespace='clients')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clients/models.py
from django.db import models

from default import NULLABLE
from users.models import User


class Client(models.Model):
    first_name = models.CharField(max_length=50, verbose_name='имя')
    second_name = models.CharField(max_length=50, verbose_name='фамилия')
    sur_name = models.CharField(max_length=50, verbose_name='отчество')
    email = models.EmailField(max_length=150, verbose_name='почта', unique=True)
    comments = models.TextField(verbose_name='коментарии', **NULLABLE)
    user_creator = models.EmailField(verbose_name='создатель', **NULLABLE)

    def __str__(self):
        return f'{self.second_name} {self.first_name} {self.sur_name}'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'

clients/forms.py
from django import forms

from clients.models import Client


class ClientsForm(forms.ModelForm):
    class Meta:
        model = Client
        exclude = ('user_creator',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

clients/views.py
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from clients.models import Client
from clients.forms import ClientsForm
from mailings.models import LogMailings


class ClientsListView(ListView):
    model = Client
    template_name = 'clients/client_list.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        return context_data


class ClientsCreateView(CreateView):
    model = Client
    form_class = ClientsForm

    def form_valid(self, form):
        self.object = form.save()
        self.object.user_creator = self.request.user.email
        self.object.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('clients:clients_list')


class ClientsUpdateView(UpdateView):
    model = Client
    form_class = ClientsForm

    def get_success_url(self):
        return reverse('clients:clients_list')


class ClientsDetailView(DetailView):
    model = Client
    template_name = 'clients/client_detail.html'


class ClientsDeleteView(DeleteView):
    model = Client

    def get_success_url(self):
        return reverse('clients:clients_list')


class LogMailingsView(ListView):
    model = LogMailings
    template_name = 'mailings/log_mailings_list.html'

clients/templates/clients/client_confirm_delete.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-3">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить продукт "{{object.email}} ?"</p>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-danger">
                            Подтвердить
                        </button>
                        <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'clients:clients_list' %}">
                            ОТМЕНА
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

clients/templates/clients/client_detail.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ object.second_name}} {{ object.first_name }} {{ object.sur_name }}</h5>

                <p class="card-text">Email: {{ object.email}}</p>
                <p class="card-text">Описание клиента: {{ object.comments}}</p>
                <a class="btn btn-outline-primary" href="{% url 'clients:clients_list' %}">
                    Назад
                </a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

clients/templates/clients/client_form.html
{% extends 'mailings/base.html' %}

{% block content %}
    <div class="col-12">
        <form method="post">
            <div class="row">
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                Создать
                            </button>
                            <a class="btn btn-outline-primary" href="{% url 'clients:clients_list' %}">
                                Назад
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

clients/templates/clients/client_list.html
{% extends 'mailings/base.html' %}

{% block content %}

    {% if user.is_active %}
        <div class="row">
            <div class="col-12">
                <div class="row">
                    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'clients:clients_create' %}">
                        Регистрация клиента
                    </a>
                </div>
            </div>


        </div>
        <br>


        <div class="row">
            {% for object in object_list %}
                {% if user.email == object.user_creator %}
                    <div class="col-3">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">{{ object.first_name }}</h5>
                                <p class="card-text">{{ object.second_name }}</p>
                                <p class="card-text">{{ object.email }}</p>
                                <a class="btn btn-lg btn-block btn-outline-primary"
                                   href="{% url 'clients:clients_detail' object.pk %}">Просмотреть</a>
                                <a class="btn btn-lg btn-block btn-outline-primary"
                                   href="{% url 'clients:clients_update' object.pk %}">Редактировать</a>
                                <a class="btn btn-lg btn-block btn-outline-primary"
                                   href="{% url 'clients:clients_delete' object.pk %}">Удалить</a>
                            </div>
                        </div>
                    </div>
                {% endif %}

            {% endfor %}
        </div>
    {% else %}
        <p align="center">Вы не авторизовались. Доступа к продуктам нет.</p>
    {% endif %}

{% endblock %}